loc_names = {'New York City': 'NY, USA', 
            'London': 'England, UK', 
            'Los Angeles': 'CA, USA', 
            'England': 'UK', 
            'New York': 'NY, USA',
            'NYC': 'NY, USA',
            'USA': 'USA',
            'LONDON': 'England, UK', 
            'California': 'CA, USA', 
            'UK': 'UK',
            'United Kingdom': 'UK',
            'Atlanta': 'GA, USA', 
            'Boston': 'MA, USA', 
            'Liverpool': 'England, UK', 
            'Texas': 'TX, USA', 
            'nyc': 'NY, USA', 
            'new york': 'NY, USA',
            'los angeles': 'CA, USA', 
            'NEW YORK CITY': 'NY, USA', 
            'Ohio': 'OH, USA', 
            'chicago': 'IL, USA', 
            'Chicago': 'IL, USA',
            'london': 'England, UK', 
            'Nyc': 'NY, USA', 
            ' sailors': None, 
            'Glasgow': 'Scotland, UK', 
            'england': 'England, UK', 
            'Houston': 'TX, USA',
            'usa': 'USA', 
            'Dallas': 'TX, USA', 
            'uk': 'UK', 
            'texas': 'TX, USA', 
            'ATLANTA': 'GA, USA', 
            'Austin': 'TX, USA', 
            'LOS ANGELES': 'CA, USA',
            'Los angeles': 'CA, USA', 
            'austin': 'TX, USA', 
            'liverpool': 'England, UK', 
            'TEXAS': 'TX, USA', 
            'new york city': 'NY, USA',
            'atlanta': 'GA, USA', 
            'california': 'CA, USA', 
            'NEW YORK': 'NY, USA', 
            'HOUSTON': 'TX, USA', 
            'ohio': 'OH, USA', 
            'Usa': 'USA', 
            'CALIFORNIA': 'CA, USA', 
            'glasgow': 'Scotland, UK', 
            'houston': 'TX, USA', 
            'Uk': 'UK', 
            'BOSTON': 'MA, USA', 
            'CHICAGO': 'IL, USA',
            'GLASGOW': 'Scotland, UK', 
            'boston': 'MA, USA', 
            'OHIO': 'OH, USA', 
            'New York CIty': 'NY, USA', 
            'New york': 'NY, USA',
            'Los Ángeles': 'CA, USA', 
            'CHICAGØ': 'IL, USA', 
            'united kingdom': 'UK', 
            'oHIo': 'OH, USA', 
            'USa': 'USA',
            'New York city': 'NY, USA', 
            'dallas': 'TX, USA', 
            'nYc': 'NY, USA', 
            'United kingdom': 'UK', 
            'ⓊⓀ': 'UK',
            ' we did this': None, 
            'ENGLAND': 'UK', 
            'LIVERPOOL': 'England, UK', 
            'californiA': 'CA, USA',
            'ˡᵒˢ ᵃⁿᵍᵉˡᵉˢ': 'CA, USA', 
            'DALLAS': 'TX, USA', 
            'uSA': 'USA', 
            'UNITED KINGDOM': 'UK', 
            'OHio': 'OH, USA', 
            'UsA': 'USA',
            'new York city': 'NY, USA', 
            'teXas': 'TX, USA', 
            'nÿc': 'NY, USA', 
            'ⓝⓨⓒ': 'NY, USA', 
            'New york City': 'NY, USA',
            'los Angeles': 'CA, USA', 
            'new yoRk city': 'NY, USA', 
            'new York': 'NY, USA', 
            'OhIo': 'OH, USA', 
            'Løs Angeles': 'CA, USA',
            'united Kingdom': 'UK', 
            'daLLas': 'TX, USA', 
            'cAliFoRNiA': 'CA, USA', 
            'TeXas': 'TX, USA', 
            'New york city': 'NY, USA',
            'b̸o̸s̸t̸o̸n̸': 'MA, USA', 
            'LOS ÁNGELES': 'CA, USA', 
            ' learn more': None, 
            'AUSTIN': 'TX, USA',
            'ｃａｌｉｆｏｒｎｉａ': 'CA, USA', 
            'TeXaS': 'TX, USA', 
            'tExas': 'TX, USA', 
            'Chĩcagö': 'IL, USA', 
            'Ｌｏｓ Ａｎｇｅｌｅｓ': 'CA, USA', 
            'Øhiø': 'OH, USA',
            ' in fear that they may catch a cold or': None, 
            'LoNdOn': 'England, UK', 
            'hoUSTon': 'TX, USA',
            'NyC': 'NY, USA', 
            ' folks." -Joe Biden on China': None, 
            'Los Angèles': 'CA, USA', 
            'TexAs': 'TX, USA',
            'United KIngdom': 'UK', 
            'CAlifornia': 'CA, USA', 
            'nEW yoRk': 'NY, USA', 
            'CaliforniA': 'CA, USA', 
            'BoStOn': 'MA, USA',
            'LIverpool': 'England, UK'}